[DEV-1404] Refactor Energy Datastore to Implement Updated SDK Interface
zepben/energy-datastore pull request #9
Opened 2024-08-28 05:57 UTC by clydeu

# Description

Changes are mainly to update the EWB SDK version and the usage of EwbDataFilePaths class

# Associated tasks
https://github.com/zepben/ewb-sdk-jvm/pull/178

# Test Steps

Testing can be achieved by using the affected classes directly.

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
- [x] I have performed a self review of my own code (including checking issues raised when creating the PR).
- [x] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.
- [x] I have commented my code in any hard-to-understand or hacky areas.
- [x] I have handled all new warnings generated by the compiler or IDE.
- [x] I have rebased onto the target branch (usually main).

### Documentation
- [x] I have updated the changelog.
- [ ] ~I have updated any documentation required for these changes.~
Repo has no documentation.

# Breaking Changes
- [x] I have considered if this is a breaking change and will communicate it with other team members if so.

No breaking change.

2024-08-28 05:57 UTC, ryanjcoleman commented
Task linked: [DEV-1404 Refactor Energy Datastore to Implement Updated SDK Interface](https://app.clickup.com/t/6929263/DEV-1404)

2024-08-28 06:01 UTC, clydeu commented
Test is failing because the SDK version has not been uploaded to the package repo.

2024-08-29 05:04 UTC, charlta requested changes

2024-08-29 05:04 UTC, charlta commented on pom.xml
> +            <version>0.23.0-SNAPSHOT5</version>
todo: This will need to be updated once your other PR is merged to match the deployed version number, then this is good to go.

2024-09-02 00:01 UTC, charlta approved these changes

2024-09-02 00:01 UTC, merged